# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Tissue Directory
    url: https://directory.biobankinguk.org/version


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Health-Informatics-UoN/tdcc-status/refs/heads/master/assets/logo.png
  name: Tissue Directory Status
  introTitle: "**Tissue Directory Status** is the open-source uptime monitor and status page for TDCC."
  introMessage: Our team are monitoring and alerted by the status of this page.
  theme: night
  navbar:
    - title: Tissue Directory Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - AndyRae
